### PR TITLE
add a dockerfile -- with a repman user

### PR DESCRIPTION
**Pull request by Thorsieger**
Since https://github.com/signal18/replication-manager/commit/870269c449d6f0786f8245744a62c5cc6dff6075 a docker build cannot work in the docker subdirectory (it needs to be at the root of the repository).

The latest version on [dockerhub](https://hub.docker.com/r/signal18/replication-manager) is stuck at repman 2.3.12

I use the [already existing dockerfile](https://github.com/signal18/replication-manager/blob/develop/docker/Dockerfile) as a template and add a specific user to not run as root.

I also add some apt cleanup to reduce image size

### CODE REVIEW

**Comment by tanji** [comment]
Hi @Thorsieger , could you clarify the goal of this PR?

**Comment by Thorsieger** [comment]
Hi!

As I say in the first message the docker version of repman cannot be build since dockerfiles were moved to a subdir. You have to manually move the file to the root of the projet :/

And the second think is : running a container with the root user is not a "best practice" it's better to use a dedicated user, it's also about security (being root in container can makes you root on host )

If you want I can update the arb and pro dockerfile too, but because I'm not using their I'm not sure if I can validate if they work correctly.

**Comment by tanji** [comment]
Hi @Thorsieger,

> As I say in the first message the docker version of repman cannot be build since dockerfiles were moved to a subdir. You have to manually move the file to the root of the projet :/

No, it has nothing to do with that. Repman 2.3.12 is 2 months old and we moved the Dockerfile to a subdir 5 years ago ;)

You can build files in a subdir with `docker build [path to dockerfile]`. That is what we do.
The reason why the version is out of date is different. There are apparently some build issues due to a missing file, but we will fix it and the Docker image will be up to date soon. Thanks a lot for reporting this!

> And the second think is : running a container with the root user is not a "best practice" it's better to use a dedicated user, it's also about security (being root in container can makes you root on host )

I agree with that, it's not the best security practice. Therefore we will change it according to your request :)
I will close the PR and do the necessary changes on our side.
Thanks for your suggestion!

**Comment by Thorsieger** [comment]
You are sure you can build inside subdir ?

```
thorsieger@thorsieger ~/Documents/github.com/replication-manager (develop) $ docker build docker           
[+] Building 0.6s (12/19)                                                                                                                                             docker:default
 => [internal] load .dockerignore                                                                                                                                               0.0s
 => => transferring context: 2B                                                                                                                                                 0.0s
 => [internal] load build definition from Dockerfile                                                                                                                            0.0s
 => => transferring dockerfile: 1.41kB                                                                                                                                          0.0s
 => [internal] load metadata for docker.io/library/debian:buster-slim                                                                                                           0.4s
 => [internal] load metadata for docker.io/library/golang:1.20-bullseye                                                                                                         0.4s
 => [stage-1 1/9] FROM docker.io/library/debian:buster-slim@sha256:8e5da7fd9aef8c0b3f23bb8c3f391667b50929984b7daa666ea1c7730f3b73b9                                             0.0s
 => [internal] load build context                                                                                                                                               0.0s
 => => transferring context: 129B                                                                                                                                               0.0s
 => [builder 1/5] FROM docker.io/library/golang:1.20-bullseye@sha256:c4c28e1d66ff6e8bfa51543940688d512fc1c128325149021e123bd642a47e55                                           0.0s
 => => resolve docker.io/library/golang:1.20-bullseye@sha256:c4c28e1d66ff6e8bfa51543940688d512fc1c128325149021e123bd642a47e55                                                   0.0s
 => CACHED [stage-1 2/9] RUN mkdir -p         /etc/replication-manager         /etc/replication-manager/cluster.d         /var/lib/replication-manager                          0.0s
 => CACHED [builder 2/5] RUN mkdir -p /go/src/github.com/signal18/replication-manager                                                                                           0.0s
 => CACHED [builder 3/5] WORKDIR /go/src/github.com/signal18/replication-manager                                                                                                0.0s
 => CACHED [builder 4/5] COPY . .                                                                                                                                               0.0s
 => ERROR [builder 5/5] RUN make osc cli                                                                                                                                        0.2s
------
 > [builder 5/5] RUN make osc cli:
0.198 make: *** No rule to make target 'osc'.  Stop.
------
Dockerfile:8
--------------------
   6 |     COPY . .
   7 |     
   8 | >>> RUN make osc cli
   9 |     
  10 |     FROM debian:buster-slim
--------------------
ERROR: failed to solve: process "/bin/sh -c make osc cli" did not complete successfully: exit code: 2
thorsieger@thorsieger ~/Documents/github.com/replication-manager (develop) $ docker build docker/
[+] Building 0.7s (12/19)                                                                                                                                             docker:default
 => [internal] load build definition from Dockerfile                                                                                                                            0.0s
 => => transferring dockerfile: 1.41kB                                                                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                                                               0.0s
 => => transferring context: 2B                                                                                                                                                 0.0s
 => [internal] load metadata for docker.io/library/debian:buster-slim                                                                                                           0.4s
 => [internal] load metadata for docker.io/library/golang:1.20-bullseye                                                                                                         0.4s
 => [stage-1 1/9] FROM docker.io/library/debian:buster-slim@sha256:8e5da7fd9aef8c0b3f23bb8c3f391667b50929984b7daa666ea1c7730f3b73b9                                             0.0s
 => [internal] load build context                                                                                                                                               0.0s
 => => transferring context: 129B                                                                                                                                               0.0s
 => [builder 1/5] FROM docker.io/library/golang:1.20-bullseye@sha256:c4c28e1d66ff6e8bfa51543940688d512fc1c128325149021e123bd642a47e55                                           0.0s
 => => resolve docker.io/library/golang:1.20-bullseye@sha256:c4c28e1d66ff6e8bfa51543940688d512fc1c128325149021e123bd642a47e55                                                   0.0s
 => CACHED [stage-1 2/9] RUN mkdir -p         /etc/replication-manager         /etc/replication-manager/cluster.d         /var/lib/replication-manager                          0.0s
 => CACHED [builder 2/5] RUN mkdir -p /go/src/github.com/signal18/replication-manager                                                                                           0.0s
 => CACHED [builder 3/5] WORKDIR /go/src/github.com/signal18/replication-manager                                                                                                0.0s
 => CACHED [builder 4/5] COPY . .                                                                                                                                               0.0s
 => ERROR [builder 5/5] RUN make osc cli                                                                                                                                        0.2s
------
 > [builder 5/5] RUN make osc cli:
0.218 make: *** No rule to make target 'osc'.  Stop.
------
Dockerfile:8
--------------------
   6 |     COPY . .
   7 |     
   8 | >>> RUN make osc cli
   9 |     
  10 |     FROM debian:buster-slim
--------------------
ERROR: failed to solve: process "/bin/sh -c make osc cli" did not complete successfully: exit code: 2
thorsieger@thorsieger ~/Documents/github.com/replication-manager (develop) $ docker build docker/Dockerfile.arb 
[+] Building 0.0s (0/0)                                                                                                                                               docker:default
ERROR: unable to prepare context: path "docker/Dockerfile.arb" not found
thorsieger@thorsieger ~/Documents/github.com/replication-manager (develop) $ docker build docker/Dockerfile.pro 
[+] Building 0.0s (0/0)                                                                                                                                               docker:default
ERROR: unable to prepare context: path "docker/Dockerfile.pro" not found
thorsieger@thorsieger ~/Documents/github.com/replication-manager (develop) $ docker build docker/Dockerfile    
[+] Building 0.0s (0/0)                                                                                                                                               docker:default
ERROR: unable to prepare context: path "docker/Dockerfile" not found
```

I've maybe a bad configuration

**Comment by tanji** [comment]
Your command is not going to work because you are taking the `/docker` subdir as build context, as a result all the files below this level are invisible to the build engine.

You can build by specifying the Dockerfile by name. e.g.

```
docker build . -f docker/Dockerfile
```

Hope that helps!

**Pull request closed without merging**
